---
name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.8.5
      # set-up python with cache
      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'poetry'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: poetry install --only lint
      # run linters
      - name: Run linters
        run: |
          set -o pipefail
          poetry run make lint